package Intervals.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Factorization_Constraints extends BaseConstraintsDescriptor {
  public Factorization_Constraints() {
    super(MetaAdapterFactory.getConcept(0xa53c4e1e842a41bfL, 0x8061e6593f83a038L, 0x4027a593fa5b6202L, "Intervals.structure.Factorization"));
  }

}
